export { goalFunnelFilterFields as goalFunnelFilterOptions } from "@databuddy/shared/analytics-filters";

export const filterOptions = [
	{ value: "path", label: "Page path" },
	{ value: "referrer", label: "Referrer" },
	{ value: "country", label: "Country" },
	{ value: "region", label: "Region/state" },
	{ value: "city", label: "City" },
	{ value: "timezone", label: "Timezone" },
	{ value: "language", label: "Language" },
	{ value: "device_type", label: "Device type" },
	{ value: "browser_name", label: "Browser" },
	{ value: "os_name", label: "Operating system" },
	{ value: "utm_source", label: "UTM source" },
	{ value: "utm_medium", label: "UTM medium" },
	{ value: "utm_campaign", label: "UTM campaign" },
	{ value: "provider", label: "Provider" },
	{ value: "model", label: "Model" },
	{ value: "type", label: "Call type" },
	{ value: "finish_reason", label: "Finish reason" },
	{ value: "error_name", label: "Error name" },
	{ value: "http_status", label: "HTTP status" },
	{ value: "user_id", label: "User ID" },
	{ value: "trace_id", label: "Trace ID" },
] as const;
