import { vi } from "vitest";

export function createRedisModuleMock(
	overrides: Record<string, unknown>
): Record<string, unknown> {
	return {
		AGENT_CONTEXT_SNAPSHOT_PREFIX: "agent:context-snapshot",
		INSIGHTS_DISPATCH_JOB_NAME: "insights-dispatch",
		INSIGHTS_GENERATE_WEBSITE_JOB_NAME: "insights-generate-website",
		INSIGHTS_JOB_OPTIONS: {},
		INSIGHTS_JOB_TIMEOUT_MS: 120_000,
		INSIGHTS_QUEUE_ENV_PREFIX: "INSIGHTS",
		INSIGHTS_QUEUE_NAME: "insights-generation",
		UPTIME_CHECK_JOB_NAME: "uptime-check",
		UPTIME_JOB_OPTIONS: {},
		UPTIME_JOB_TIMEOUT_MS: 60_000,
		UPTIME_QUEUE_NAME: "uptime-checks",
		abandonCachedLinkMutation: vi.fn(async () => true),
		activeStreamKey: (id: string) => `active:${id}`,
		appendStreamChunk: vi.fn(async () => undefined),
		beginCachedLinkMutation: vi.fn(async () => ({
			state: "acquired",
			token: "test-token",
		})),
		cacheNamespaces: {
			agentTelemetryWebsiteExists: "agent-telemetry:website-exists",
			apiKeyByHash: "api-key-by-hash",
			apiKeyOwnerId: "api_key_owner_id",
			billingOwner: "rpc:billing_owner",
			flag: "flag",
			flagsClient: "flags-client",
			flagsDefinitions: "flags-definitions",
			flagsUser: "flags-user",
			mcpInsights: "mcp:insights",
			memberRole: "rpc:member_role",
			organizationOwner: "rpc:org_owner",
			organizationRole: "rpc:org_role",
			slackChannelBinding: "slack-channel-binding",
			slackIntegrationByTeam: "slack-integration-by-team",
			statusPage: "status-page",
			userPreferences: "user-prefs",
			websiteById: "website_by_id",
			websiteCache: "website-cache",
			websiteDomain: "website-domain",
			websiteDomainsBatch: "website-domains-batch",
			websiteWithOwner: "website_with_owner_v2",
		},
		cacheTags: {
			billingOwner: (ownerId: string) => `billing-owner:${ownerId}`,
			flagClient: (clientId: string) => `flag-client:${clientId}`,
			flagKey: (clientId: string, flagKey: string) =>
				`flag-key:${clientId}:${flagKey}`,
			flagUser: (clientId: string, userId: string) =>
				`flag-user:${clientId}:${userId}`,
			organization: (organizationId: string) =>
				`organization:${organizationId}`,
			website: (websiteId: string) => `website:${websiteId}`,
		},
		cacheable: <T extends (...args: never[]) => unknown>(fn: T) => fn,
		clearActiveStream: vi.fn(async () => undefined),
		closeInsightsQueue: vi.fn(async () => undefined),
		closeUptimeQueue: vi.fn(async () => undefined),
		createDrizzleCache: () => ({}),
		enqueueInsightsResume: vi.fn(async () => "queued"),
		finishCachedLinkMutation: vi.fn(async () => true),
		getActiveStream: vi.fn(async () => null),
		getAgentContextSnapshotKey: (
			userId: string,
			websiteId: string,
			organizationId?: string | null
		) => `agent:context-snapshot:${organizationId ?? userId}:${websiteId}`,
		getBullMQConnectionOptions: vi.fn(() => ({})),
		getBullMQWorkerConnectionOptions: vi.fn(() => ({})),
		getCacheableKey: vi.fn(
			(prefix: string, args: unknown[]) => `${prefix}:${JSON.stringify(args)}`
		),
		getCachedLink: vi.fn(async () => null),
		getInsightsQueue: vi.fn(() => ({})),
		getLinkCacheKey: vi.fn((slug: string) => `link:${slug}`),
		getRateLimitHeaders: vi.fn(() => ({})),
		getUptimeQueue: vi.fn(() => ({})),
		insightsResumeJobId: (replyId: string) => `insights-reply-${replyId}`,
		insightsWebsiteJobId: (runId: string, websiteId: string) =>
			`insights-website-${runId}-${websiteId}`,
		invalidateAgentContextSnapshot: vi.fn(async () => 0),
		invalidateAgentContextSnapshotsForOwner: vi.fn(async () => 0),
		invalidateAgentContextSnapshotsForWebsite: vi.fn(async () => 0),
		invalidateBillingOwnerCaches: vi.fn(async () => ({
			attempted: 0,
			failed: 0,
		})),
		invalidateCacheableKey: vi.fn(async () => 0),
		invalidateCacheablePattern: vi.fn(async () => 0),
		invalidateCacheablePrefix: vi.fn(async () => 0),
		invalidateCacheableTag: vi.fn(async () => 0),
		invalidateCacheableTags: vi.fn(async () => ({ attempted: 0, failed: 0 })),
		invalidateCacheableWithArgs: vi.fn(async () => 0),
		invalidateFlagReadCaches: vi.fn(async () => ({ attempted: 0, failed: 0 })),
		invalidateGithubIntegrationCache: vi.fn(async () => undefined),
		invalidateInsightsCachesForOrganization: vi.fn(async () => ({
			attempted: 0,
			failed: 0,
		})),
		invalidateLinkCache: vi.fn(async () => undefined),
		invalidateLinkCaches: vi.fn(async () => undefined),
		invalidateOrganizationMembershipCaches: vi.fn(async () => ({
			attempted: 0,
			failed: 0,
		})),
		invalidateSlackChannelBindingCache: vi.fn(async () => undefined),
		invalidateSlackIntegrationCache: vi.fn(async () => undefined),
		invalidateStatusPageCache: vi.fn(async () => 0),
		invalidateUserPreferencesCache: vi.fn(async () => undefined),
		invalidateWebsiteReadCaches: vi.fn(async () => ({
			attempted: 0,
			failed: 0,
		})),
		isClickRecorded: vi.fn(async () => false),
		markStreamDone: vi.fn(async () => undefined),
		ratelimit: vi.fn(async () => ({ success: true })),
		readStreamHistory: vi.fn(async () => []),
		setActiveStream: vi.fn(async () => undefined),
		setCachedLink: vi.fn(async () => undefined),
		setCachedLinkIfAbsent: vi.fn(async () => true),
		setCachedLinkNotFound: vi.fn(async () => undefined),
		setCachedLinkNotFoundIfAbsent: vi.fn(async () => true),
		shouldRecordClick: vi.fn(async () => true),
		shutdownRedis: vi.fn(async () => undefined),
		streamBufferKey: (id: string) => `stream:${id}`,
		uptimeImmediateJobId: (id: string) => `uptime:immediate:${id}`,
		uptimeSchedulerId: (id: string) => `uptime:scheduler:${id}`,
		...overrides,
	};
}
